# Generated by Django 3.2.6 on 2021-09-04 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_movies"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Movies",
            new_name="Movie",
        ),
    ]
